import type { Metadata } from "next";

const SITE_NAME = "PPIM Consulting";

/** Generated by src/app/opengraph-image.tsx. */
const SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "PPIM Consulting — licensed immigration adviser, Auckland, New Zealand",
};

/**
 * Next replaces a page's `openGraph` object wholesale rather than merging it
 * with the root layout's — including the file-based share image — so every
 * page builds the full set here.
 */
export function pageOpenGraph(
  title: string,
  description: string,
  path: string
): Metadata["openGraph"] {
  return {
    title,
    description,
    url: path,
    siteName: SITE_NAME,
    locale: "en_NZ",
    type: "website",
    images: [SHARE_IMAGE],
  };
}
